name: Build JAR

on:
  push:
    branches:
      - All-CI-CD  # Trigger on push to All-CI-CD branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Fixed: Specify version
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create output directory
        run: mkdir -p dist

      - name: Copy JAR and TXT files
        run: |
          cp target/*.jar dist/
          cp *.txt dist/  # Copy .txt files from root

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: dist/*

      # Optional: Deploy to server and restart service on push
      - name: Deploy to server and restart service
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            sudo systemctl stop fitness-app.service || true
            mkdir -p /opt/fitness-app
            rm -f /opt/fitness-app/*.jar
            rm -f /opt/fitness-app/*.txt
          EOF
          scp -i private_key -o StrictHostKeyChecking=no dist/*.jar dist/*.txt $SERVER_USER@$SERVER_IP:/opt/fitness-app/
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            sudo systemctl start fitness-app.service
            sudo systemctl enable fitness-app.service
          EOF