name: Deploy to VPS (All-CI-CD)

on:
  push:
    branches:
      - All-CI-CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Without Tests
        run: mvn clean package -DskipTests

      - name: Copy JAR and .txt Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: |
            target/*.jar
            *.txt  # Include .txt files from the root directory
          target: "~/app"  # Destination directory on the VPS


      - name: Restart Application on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo systemctl restart springboot-app
            sudo systemctl status springboot-app
